apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: eval
spec:
  type: ClusterIP
  selector:
    app: mysql
  clusterIP: 10.43.0.42
  ports:
  - protocol: TCP
    port: 3307
    targetPort: 3306
